# Generated by Django 3.2 on 2025-04-09 14:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210513_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_registration',
            name='donation_count',
            field=models.IntegerField(default=0, help_text='Number of times donated'),
        ),
        migrations.AddField(
            model_name='donor_registration',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg (minimum 45kg required for donation)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(45.0), django.core.validators.MaxValueValidator(200.0)]),
        ),
        migrations.AlterField(
            model_name='con_tact',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='con_tact',
            name='subject',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donor_registration',
            name='home_address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donor_registration',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(auto_now_add=True)),
                ('blood_volume', models.DecimalField(decimal_places=2, default=450.0, help_text='Blood volume in ml', max_digits=4)),
                ('notes', models.TextField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='polls.donor_registration')),
            ],
        ),
    ]
